"""empty message

Revision ID: 1c62683e4a42
Revises: ef0bfee8e81a
Create Date: 2022-06-01 21:02:29.558093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c62683e4a42'
down_revision = 'ef0bfee8e81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'artist_id')
    # ### end Alembic commands ###
