"""empty message

Revision ID: 67aacb98bd0c
Revises: 1c62683e4a42
Create Date: 2022-06-02 09:30:23.029215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67aacb98bd0c'
down_revision = '1c62683e4a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileID', sa.Column('uuid', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'fileID', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fileID', type_='unique')
    op.drop_column('fileID', 'uuid')
    # ### end Alembic commands ###
