"""empty message

Revision ID: d42267ffb6bc
Revises: e4a68fe0416d
Create Date: 2022-06-02 10:07:33.765327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42267ffb6bc'
down_revision = 'e4a68fe0416d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fileID_uuid_key', 'fileID', type_='unique')
    op.create_unique_constraint(None, 'fileID', ['filename'])
    op.drop_column('fileID', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileID', sa.Column('uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fileID', type_='unique')
    op.create_unique_constraint('fileID_uuid_key', 'fileID', ['uuid'])
    # ### end Alembic commands ###
