"""empty message

Revision ID: e4a68fe0416d
Revises: 67aacb98bd0c
Create Date: 2022-06-02 09:40:56.566147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a68fe0416d'
down_revision = '67aacb98bd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileID', sa.Column('filename', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fileID', 'filename')
    # ### end Alembic commands ###
